### ISSUE TITLE
Package rejected by Apple

### ISSUE THREAD

**Issue by tuxslayer** [avast/safariextz#3]
Hi, I have a question: does it work for submission to the new store (https://developer.apple.com/safari/extensions/)? 

The package built with xar 1.6.1 was rejected by Apple, so I'm wondering will this utility help.

**Comment by pavelstudeny** [comment]
I have used side loading so far, but I'll be able to tell you in about a month or two.

**Comment by NekR** [comment]
So any updates?

**Comment by pavelstudeny** [comment]
I submitted an extension on 2016-06-24 and it looks like a black hole so far - no submit confirmation, no response, submission status and progress cannot be found anywhere.
The good news is that the extension wasn't rejected because of the packer (yet).

**Comment by NekR** [comment]
Thanks for info. Sounds weird.

Do you know if this happens with all extensions? E.g. if you send an
extension packages with Safari itself, will it be processed faster?

On Jun 30, 2016 12:06, "pavelstudeny" notifications@github.com wrote:

I submitted an extension on 2016-06-24 and it looks like a black hole so
far - no submit confirmation, no response, submission status and progress
cannot be found anywhere.
The good news is that the extension wasn't rejected because of the packer
(yet).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/avast/safariextz/issues/3#issuecomment-229604046, or mute
the thread
https://github.com/notifications/unsubscribe/ABIlkTGQc-Vy1eZpGmsB0yb730ipIr3Vks5qQ4cQgaJpZM4HZD1q
.

**Comment by pavelstudeny** [comment]
Just got a response from Apple:

> During our review of your extension we found that it was not built with a new enough version of the Safari Extension Builder. Please build your Safari Extension with Safari 9 on Yosemite or El Capitan.

I can see two solutions:
- update the underlying packager (https://github.com/robertknight/xar-js) to produce an up-to-date looking format
- use a different mechanism, perhaps the regular xar 1.7+ utility and some sign tool

**Comment by robertknight** [comment]
@pavelstudeny - Thanks for the update. If one of us can get hold of an Apple engineer who knows about the extension builder and explain what we're trying to do that would probably be the quickest way to figure out how best to proceed.

**Comment by pavelstudeny** [comment]
Seems that my contacts in Apple won't tell me. Anyway, I get the same response from Apple even when the extension is built by "Safari 9 on Yosemite or El Capitan" as requested. I will update here if anything changes.

**Comment by pavelstudeny** [comment]
Status update: it _seems_ that this is not related to the packager - I got the same results even when packing this with the latest Safari. What matters was in my case various names, that should be in sync (package name, the source directory name, ...)

**Comment by pavelstudeny** [comment]
I can confirm that packages built by this utility are acceptable by Apple. The review process ranges between a few weeks to a few months. If the package is rejected within a week, the wording of the rejection has nothing to do with the actual reason. In my case, it was the naming - package name, source directory (before packing), name inside the manifest etc..

**Comment by NekR** [comment]
@pavelstudeny thanks for the update!
